### ISSUE TITLE
FH run failed due to alignment metric being decimal

### ISSUE THREAD

**Issue by SophieS9** [AWGL/auto_qc#103]
The alignment metric value for pf_hq_median_mismatches was a decimal value for the NTC sample in run 220923_M02641_0536_000000000-KK2Y4 and therefore failed loading into the database as an integer is expected. 

Need to update following line to allow for this:
https://github.com/AWGL/auto_qc/blob/41f6386080f701a6994b3def22769a9ee4028304/qc_database/models.py#L1230

**Comment by josephhalstead** [comment]
closed in pull request #104
