### ISSUE TITLE
Update WES Panel Name in SampleSheet Generator

### ISSUE THREAD

**Issue by millardkieron** [AWGL/auto_qc#184]
Need to update the wes panel name in utils.py script for SampleSheet generator as its currently applying the WGS panel instead for paediatric_disorders_green instead of paediatric_disorders_green_wes.

**Comment by millardkieron** [comment]
Believe to have fixed issue - Referral Type SHIRE name saved as PANEL WES SKELETAL DYSPLASIAS rather than PANEL WES Skeletal dysplasias. Changed this in admin but will leave open until successful WES run uploaded. Worked on local system.

**Comment by millardkieron** [comment]
Samplesheet has passed through since this fix with no errors. Issue closed.

**Comment by ASendellPrice** [comment]
paediatric_disorders_green panel is still being applied automatically when paediatric_disorders_green_wes should be used. Issue reopened.
