### ISSUE TITLE
add QC metric info tab

### ISSUE THREAD

**Issue by kgrimes8** [AWGL/auto_qc#64]
From feedback received there is a general lack of understanding around QC metrics and what they are/mean for the data.

A suggested fix would be to make a simple new HTML template which is an "info" tab that has a breakdown of QC metrics and their meaning. This would be highly available to people on autoQC database to refresh their memory.

**Comment by Istaisa** [comment]
Do we still need to implement this now bioinformatics are signing off all the runs?

**Comment by josephhalstead** [comment]
We do not - closing issue
