### ISSUE TITLE
Conda env yaml not working

### ISSUE THREAD

**Issue by erikwaskiewicz** [AWGL/auto_qc#78]
I couldn't install the conda env unless I deleted the pysam line, was fine for testing the samplesheet generator but would be needed for auto_qc

**Comment by Istaisa** [comment]
I think this is a dependency clash - it builds with pysam 0.21.0, and as AutoQC just uses VariantFile from pysam this should be fine?

**Comment by Istaisa** [comment]
Issue fixed with pysam downgrade for webserver deploy #206
