### ISSUE TITLE
Ti/Tv cut off for WGS

### ISSUE THREAD

**Issue by SophieS9** [AWGL/auto_qc#85]
The current Ti/Tv cut off for WGS and FastWGS in GRCh38 has been based on previous runs with the value taken from the per sample variant call metrics file. However, AutoQC looks at the combined whole run variant call metrics file, which has a differing value. Need to adjust cut off to reflect combined value (PREFILTER) from previous runs.

**Comment by josephhalstead** [comment]
closed in pull request #98
