### ISSUE TITLE
NTC contamination in TSO500 DNA needs updating

### ISSUE THREAD

**Issue by LauraMcCluskey7** [AWGL/auto_qc#99]
The TSO500 pipeline needs to be updated to include samtools to calculate the number of reads using the bam files.  Once this is complete, the ntc contamination can be calculated using these values, and displayed in the autoqc database

**Comment by Istaisa** [comment]
New GRCh38 TSO500 DNA pipeline does NTC contamination, AutoQC already updated + live.
